baseURL = 'https://gitkodachi.github.io/'
languageCode = 'en-us'
title = 'Octocat Code'

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "kategori"
  weight = 100

[[related.indices]]
  name = "topik"
  weight = 100

[[related.indices]]
  name = "series"
  weight = 80

[[related.indices]]
  name = "software"
  weight = 80

[taxonomies]
  kategori = "kategori"
  topik = "topik"
  tutorial = "tutorial"
  software = "software"
  buku = "buku"

[params.mermaid]
  enable = true
  theme = "forest"
  align = "center"
  securityLevel = "loose"
  fontFamily = "'JetBrains Mono', monospace"
  darkMode = true
  flowchart = "{ useMaxWidth: false }"

[pagination]
  paperSize = 6

[outputFormats]
  [outputFormats.SearchIndex]
    name = "SearchIndex"
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "SearchIndex"]


[markup]
  [markup.goldmark]
  [markup.goldmark.extensions]
      footnote = true
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    style = "dracula"
    lineNumbers = true
    pygmentsStyle = "solarized"
