baseURL = 'https://gitkodachi.github.io/'
languageCode = 'en-us'
title = 'Octocat Code'

[pagination]
  paperSize = 6

[outputFormats]
  [outputFormats.SearchIndex]
    name = "SearchIndex"
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "SearchIndex"]


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false